// <auto-generated />
using System;
using DataAccessObjects;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessObjects.Migrations
{
    [DbContext(typeof(QuizManagementDbContext))]
    [Migration("20260618163553_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessObjects.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Answers__3214EC0718E562F7");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("BusinessObjects.Deck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id")
                        .HasName("PK__Decks__3214EC07F540EDFA");

                    b.HasIndex("SubjectId");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("BusinessObjects.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("DeckId")
                        .HasColumnType("int");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id")
                        .HasName("PK__Question__3214EC079D8AB6B4");

                    b.HasIndex("DeckId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("BusinessObjects.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id")
                        .HasName("PK__Subjects__3214EC073667D612");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "Name", "UserId" }, "IX_Subjects_Name_UserId")
                        .IsUnique()
                        .HasFilter("([IsDeleted]=(0))");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("BusinessObjects.TestHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("DeckId")
                        .HasColumnType("int");

                    b.Property<double>("Percentage")
                        .HasColumnType("float");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id")
                        .HasName("PK__TestHist__3214EC07D6370CED");

                    b.HasIndex("DeckId");

                    b.HasIndex("UserId");

                    b.ToTable("TestHistories");
                });

            modelBuilder.Entity("BusinessObjects.TestResultDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int?>("SelectedAnswerId")
                        .HasColumnType("int");

                    b.Property<int>("TestHistoryId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__TestResu__3214EC07BD567949");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SelectedAnswerId");

                    b.HasIndex("TestHistoryId");

                    b.ToTable("TestResultDetails");
                });

            modelBuilder.Entity("BusinessObjects.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SecurityStamp")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC077068E03B");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BusinessObjects.Answer", b =>
                {
                    b.HasOne("BusinessObjects.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Answers_Questions");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("BusinessObjects.Deck", b =>
                {
                    b.HasOne("BusinessObjects.Subject", "Subject")
                        .WithMany("Decks")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Decks_Subjects");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("BusinessObjects.Question", b =>
                {
                    b.HasOne("BusinessObjects.Deck", "Deck")
                        .WithMany("Questions")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Questions_Decks");

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("BusinessObjects.Subject", b =>
                {
                    b.HasOne("BusinessObjects.User", "User")
                        .WithMany("Subjects")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Subjects_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObjects.TestHistory", b =>
                {
                    b.HasOne("BusinessObjects.Deck", "Deck")
                        .WithMany("TestHistories")
                        .HasForeignKey("DeckId")
                        .IsRequired()
                        .HasConstraintName("FK_TestHistories_Decks");

                    b.HasOne("BusinessObjects.User", "User")
                        .WithMany("TestHistories")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_TestHistories_Users");

                    b.Navigation("Deck");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObjects.TestResultDetail", b =>
                {
                    b.HasOne("BusinessObjects.Question", "Question")
                        .WithMany("TestResultDetails")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("FK_Details_Question");

                    b.HasOne("BusinessObjects.Answer", "SelectedAnswer")
                        .WithMany("TestResultDetails")
                        .HasForeignKey("SelectedAnswerId")
                        .HasConstraintName("FK_Details_Answer");

                    b.HasOne("BusinessObjects.TestHistory", "TestHistory")
                        .WithMany("TestResultDetails")
                        .HasForeignKey("TestHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Details_History");

                    b.Navigation("Question");

                    b.Navigation("SelectedAnswer");

                    b.Navigation("TestHistory");
                });

            modelBuilder.Entity("BusinessObjects.Answer", b =>
                {
                    b.Navigation("TestResultDetails");
                });

            modelBuilder.Entity("BusinessObjects.Deck", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("TestHistories");
                });

            modelBuilder.Entity("BusinessObjects.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("TestResultDetails");
                });

            modelBuilder.Entity("BusinessObjects.Subject", b =>
                {
                    b.Navigation("Decks");
                });

            modelBuilder.Entity("BusinessObjects.TestHistory", b =>
                {
                    b.Navigation("TestResultDetails");
                });

            modelBuilder.Entity("BusinessObjects.User", b =>
                {
                    b.Navigation("Subjects");

                    b.Navigation("TestHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
